import { useEffect, useState } from "react";
import API from "../services/api";
import { FaChartPie, FaClock, FaRecycle, FaFileAlt } from "react-icons/fa";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [userRole, setUserRole] = useState(null);

  useEffect(() => {
    const storedUser = JSON.parse(localStorage.getItem("user"));
    setUserRole(storedUser?.role);
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await API.get("/reports");
      setReports(res.data);
    } catch (err) {
      console.error("Failed to fetch reports:", err);
    }
  };

  const handleGenerate = async () => {
    try {
      await API.post("/reports/generate");
      alert("Report generated!");
      fetchReports();
    } catch (err) {
      alert("Only admins can generate reports.");
    }
  };

  return (
    <div className="max-w-5xl mx-auto p-6 min-h-screen">
      <h1 className="text-3xl font-bold mb-6 text-green-700 flex items-center gap-2">
        <FaFileAlt /> Waste Management Reports
      </h1>

      {/* Admin Only Button */}
      {userRole === "admin" && (
        <button
          onClick={handleGenerate}
          className="bg-green-600 text-white px-5 py-3 rounded-md hover:bg-green-700 transition mb-8 shadow flex items-center gap-2"
        >
          <FaFileAlt /> Generate New Report
        </button>
      )}

      {/* No Reports */}
      {reports.length === 0 ? (
        <p>No reports available.</p>
      ) : (
        <>
          {/* Summary Section */}
          <h2 className="text-xl font-semibold text-green-700 mb-4">Summary</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
            {/* Total Waste */}
            <div className="bg-white shadow p-4 rounded-lg border-l-4 border-green-600">
              <div className="flex items-center gap-3">
                <FaRecycle className="text-green-600 text-3xl" />
                <div>
                  <p className="text-gray-600 text-sm">Total Waste</p>
                  <p className="text-2xl font-bold">
                    {reports[reports.length - 1].total_waste} kg
                  </p>
                </div>
              </div>
            </div>

            {/* Recyclable Percentage */}
            <div className="bg-white shadow p-4 rounded-lg border-l-4 border-yellow-500">
              <div className="flex items-center gap-3">
                <FaChartPie className="text-yellow-500 text-3xl" />
                <div>
                  <p className="text-gray-600 text-sm">Recyclable Rate</p>
                  <p className="text-2xl font-bold">
                    {reports[reports.length - 1].recyclable_percentage.toFixed(2)}%
                  </p>
                </div>
              </div>
            </div>

            {/* Households */}
            <div className="bg-white shadow p-4 rounded-lg border-l-4 border-blue-500">
              <div className="flex items-center gap-3">
                <FaClock className="text-blue-500 text-3xl" />
                <div>
                  <p className="text-gray-600 text-sm">Households Reached</p>
                  <p className="text-2xl font-bold">
                    {reports[reports.length - 1].households_reached}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Detailed Reports */}
          <h2 className="text-xl font-semibold text-green-700 mb-4">Report Details</h2>

          <div className="space-y-4">
            {reports.map((rep, i) => (
              <div
                key={i}
                className="bg-white shadow p-5 rounded-lg border-l-4 border-green-600"
              >
                <h3 className="text-lg font-bold text-green-700 mb-2">
                  Report #{i + 1}
                </h3>

                <p><b>Total Waste:</b> {rep.total_waste} kg</p>
                <p><b>Recyclable %:</b> {rep.recyclable_percentage?.toFixed(2)}%</p>
                <p><b>Households Reached:</b> {rep.households_reached}</p>

                <p><b>Status:</b> 
                  <span className="ml-2 px-2 py-1 rounded bg-green-100 text-green-700 text-sm">
                    Completed
                  </span>
                </p>

                {rep.generated_by && (
                  <p><b>Generated By:</b> {rep.generated_by}</p>
                )}

                {rep.createdAt && (
                  <p className="text-sm text-gray-500 mt-2">
                    {new Date(rep.createdAt).toLocaleString()}
                  </p>
                )}
              </div>
            ))}
          </div>

          {/* Trend Analysis */}
          <h2 className="text-xl font-semibold text-green-700 mt-10 mb-4">Trend Analysis</h2>
          <div className="bg-white shadow p-5 rounded-lg">
            <ul className="list-disc ml-5 space-y-2 text-gray-700">
              <li>
                Waste levels are{" "}
                {reports[0].total_waste > reports[reports.length - 1].total_waste
                  ? "decreasing"
                  : "increasing"}{" "}
                over time.
              </li>
              <li>
                Recycling efficiency is{" "}
                {reports[0].recyclable_percentage >
                reports[reports.length - 1].recyclable_percentage
                  ? "declining"
                  : "improving"}{" "}
                compared to previous months.
              </li>
              <li>
                Household participation is growing, indicating better community engagement.
              </li>
            </ul>
          </div>
        </>
      )}
    </div>
  );
}
