import { useEffect, useState } from "react";
import API from "../services/api";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [userRole, setUserRole] = useState(null);

  useEffect(() => {
    const storedUser = JSON.parse(localStorage.getItem("user"));
    setUserRole(storedUser?.role);
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await API.get("/reports");
      setReports(res.data);
    } catch (err) {
      console.error("Failed to fetch reports:", err);
    }
  };

  const handleGenerate = async () => {
    try {
      await API.post("/reports/generate");
      alert("Report generated!");
      fetchReports();
    } catch (err) {
      alert("Only admins can generate reports.");
    }
  };

  return (
    <div className="max-w-5xl mx-auto p-6">
      <h1 className="text-2xl font-bold mb-6 text-green-700">Reports</h1>

      {userRole === "admin" && (
        <button
          onClick={handleGenerate}
          className="bg-green-600 text-white px-4 py-2 rounded mb-6 hover:bg-green-700"
        >
          Generate Report
        </button>
      )}

      {reports.length === 0 ? (
        <p>No reports available.</p>
      ) : (
        <div className="space-y-4">
          {reports.map((rep, i) => (
            <div key={i} className="bg-white shadow p-4 rounded-lg border-l-4 border-green-600">
              <p><b>Total Waste:</b> {rep.total_waste} kg</p>
              <p><b>Recyclable %:</b> {rep.recyclable_percentage?.toFixed(2)}%</p>
              <p><b>Households:</b> {rep.households_reached}</p>
              {rep.generated_by && <p><b>Generated By:</b> {rep.generated_by}</p>}
              {rep.createdAt && (
                <p className="text-sm text-gray-500">
                  {new Date(rep.createdAt).toLocaleString()}
                </p>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
